### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by yannickwurm** [auton1/LDhat#1]
hey, 
how should we cite ldhat?
thanks!
yannick

**Comment by mcvean** [comment]
The current version of LDhat is best referenced by
http://www.ncbi.nlm.nih.gov/pubmed/17623807

The original paper (which included the test for recombination) was
http://www.ncbi.nlm.nih.gov/pubmed/11901136

And the first version with variable recombination rate was:
 http://www.ncbi.nlm.nih.gov/pubmed/15105499

**Comment by yannickwurm** [comment]
Super - thanks gil!

**Comment by fuyiwy** [comment]
hello, l know you can use LDhat smoothly by browsing this website, can you tell me how l can do about below error,  
first of all, l use convert command and obtain the sites.txt and locs.txt file successfully, next, l use command" pairwise -seq myseq.fas -loc locs.txt" , then, the error is as follows:
"sequence read successfully
run-time error
Lseq and loca disagree
.. now exiting to system"
any help is appreciated!
@yannickwurm

**Comment by mcvean** [comment]
The -seq flag should be followed by sites.txt.

On 20 Jun 2017, at 01:48, fuyiwy <notifications@github.com<mailto:notifications@github.com>> wrote:


hello, l know you can use LDhat smoothly by browsing this website, can you tell me how l can do about below error,
first of all, l use convert command and obtain the sites.txt and locs.txt file successfully, next, l use command" pairwise -seq myseq.fas -loc locs.txt" , then, the error is as follows:
"sequence read successfully
run-time error
Lseq and loca disagree
.. now exiting to system"
any help is appreciated!
@yannickwurm<https://github.com/yannickwurm>

-

**Comment by fuyiwy** [comment]
Thanks a lot.
