### ISSUE TITLE
How convert result of rhomap to centimorgan (cM)

### ISSUE THREAD

**Issue by KazegamiKuon** [auton1/LDhat#18]
Dear Drs. Auton and Mcvean

I'm new in bioinformatics and I have read paper "Recombination rate estimation in the presence of hotspots"

I was trying apply your _rhomap_ into my genome set and got some result 
But I don't know how can I convert it (4Ner/kb) to centimorgan.

I'm trying test in your dataset that written in paper but it not available right now (or I haven't find it yet). However when I try in dataset MS32  in HapMap phase II, CEU and compare it with figure 6 in paper (I know it's different data) after convert to centimorgan by formula (value/4Ne)*1000 and got so small value that so different with figure 6

Can you help me, how can I convert result to centimorgan, it's formula?

Hope I asked at right place.

Thanks! 
ps: Your package help me so much, thanks tooo

**Comment by mcvean** [comment]
LDhat (interval) and rhomap estimate recombination rates in the units of 4Ne r / kb (assuming SNP positions are in kb).  Here, r is the recombination rate in units of Morgans (M), so 0.01 is 1cM, meaning an expected number of cross-over events per meiosis of 0.01.  In humans, the typical rate of recombination is roughly 1e-8 per bp, or 1 cM / Mb.  

To convert from 4 Ne r / kb to cM / Mb you need an estimate of Ne.  In humans, this is typically c. 10,000.  So if a region is estimated to have a recombination rate of x (in units of 4 Ne r / kb), this would imply 2.5 x in units of cM /Mb (multiply by 1000 to get to units of Mb, by another hundred to go from M to cM and divide by 40,000 to eliminate 4 Ne).

I hope this makes sense.

**Comment by KazegamiKuon** [comment]
Ohhhhh I got it! 

So we have simple formula is:  1 (4Ne_r_/kb) = 2.5 (cM/Mb) in condition (estimate) Ne = 10,000 and theta 0.01 = 1 cM

Thank you so much! I was stuck at It for 2 days.

ps:  Just to satisfy my imagination.  In laboratory conditions, can we estimate what, when or why individual will evolution in future ? I'm base background at Math and IT, when I see formula for estimate recombination rate, I though about that but not sure if it right or got some problem
